# ---------------------
# Abhi-Login
# Version 1.0
# Author: Abhiram
# ---------------------

# Encrypt Type Which type of encrypition you want plugin to use? by default its MD5 available encryption (MD5,SHA256,SHA512,BCRYPT)
Encrypt-Type: "MD5"

# Disable player movement when player is not registered/not Logged in.
Disable-Player-Movement: true

# do you want to kick player when they enter wrong password?
Kick-playeronwrongpassword: true

# Use sessions if this is true the plugin will use sessions for players!
Session: true

# Session Interval how much time you want each session to end
Session-Interval: 30