main: com.abhiram.abhilogin.Main
name: Abhi-Login
version: 2.0
author: Abhiram

commands:
  changepw:
    description: This command allow a player to change password!
  unregister:
    description: A command that allow server admins to unregister a Player!